definitions:
  models.CommentInput:
    properties:
      _id:
        type: string
      apikey:
        type: string
      comment:
        type: string
    type: object
  models.ModelError:
    properties:
      additional:
        type: string
      code:
        type: integer
      message:
        type: string
    type: object
info:
  contact: {}
  license: {}
paths: {}
